# Generated by Django 3.1.2 on 2020-10-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='object_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='spotify_id',
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
